* Encoding: UTF-8.
COMPUTE lap=RV.LAPLACE(0,1). 
EXECUTE. 
COMPUTE log=RV.LOGISTIC(0,1). 
EXECUTE. 
COMPUTE norm=RV.NORMAL(0,1). 
EXECUTE. 
COMPUTE unif=RV.UNIFORM(-1,1). 
EXECUTE.
COMPUTE a2b5=RV.BETA(2,5).
EXECUTE.
COMPUTE a5b2=RV.BETA(5,2).
EXECUTE.
COMPUTE a5b5=RV.BETA(5,5).
EXECUTE.
COMPUTE sigma0.5=RV.NORMAL(0,0.5).
EXECUTE.
COMPUTE sigma1=RV.NORMAL(0,1).
EXECUTE.
COMPUTE sigma2=RV.NORMAL(0,2).
EXECUTE.

